[package]
name = "score-stat-calc"
version = "0.1.0"
authors = ["Typas Liao <richun159@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
